-- Jalankan file ini sekali melalui Supabase SQL Editor.
-- Nama pengunjung tidak dapat dibaca oleh public/anon; owner tetap dapat melihatnya di Table Editor.

create table if not exists public.portfolio_visitors (
  id bigint generated by default as identity primary key,
  device_id uuid not null unique,
  visitor_name text not null check (char_length(visitor_name) between 2 and 60),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.portfolio_visitors enable row level security;

revoke all on table public.portfolio_visitors from anon, authenticated;

create or replace function public.register_portfolio_visitor(
  p_device_id uuid,
  p_name text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := left(trim(regexp_replace(p_name, '\s+', ' ', 'g')), 60);
  total_visitors bigint;
begin
  if char_length(clean_name) < 2 then
    raise exception 'Name must contain at least two characters';
  end if;

  insert into public.portfolio_visitors (device_id, visitor_name)
  values (p_device_id, clean_name)
  on conflict (device_id) do update
    set last_seen_at = now();

  select count(*) into total_visitors from public.portfolio_visitors;
  return total_visitors;
end;
$$;

revoke all on function public.register_portfolio_visitor(uuid, text) from public;
grant execute on function public.register_portfolio_visitor(uuid, text) to anon, authenticated;
